services:
  - type: web
    name: plainquery-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT app.app:app
    autoDeploy: true
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: uploads
      - key: PYTHON_VERSION
        value: 3.10.12